name: Releas @rhoas/spectral-ruleset
on:
  release:
    types: [created]
jobs:
  build:
    runs-on: ubuntu-latest 
    permissions:
      contents: read
      packages: write 
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-node@v2
        with:
          node-version: '12.x'
          registry-url: 'https://registry.npmjs.org'
      - name: Change to spectral directory
        run: cd spectral
      - run: npm install
      - name: Set version
        run: npm version ${{ github.event.release.tag_name }}
      - run: npm publish dist --access=public
        env:
          NODE_AUTH_TOKEN: ${{ secrets.RHOAS_NPM_TOKEN }}